---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggrepel)
```
```{r}
data <- read.csv("peanut_prod.csv")
```

```{r}
data_w <- data |> 
  janitor::clean_names() |> 
  select(year,period,state,value) |> 
  mutate(value = as.numeric(gsub(",","", value)),
         state = factor(state))
```



```{r fig.width= 8, fig.height=6, dpi=300}
data_w |>
  filter(year >2020) |> 
  filter(state %in% c("GEORGIA","ALABAMA","FLORIDA","US TOTAL")) |> 
  filter(period == "YEAR") |> 
  mutate(value_k = value/1000,
         line_type = if_else(state == "US TOTAL", "National Total", "State")) |> 
  ggplot(aes(year,value_k, color = state))+
  geom_point(size = 2)+
  geom_line(linewidth = 0.8)+
  scale_color_viridis_d(name = "Region")+
  scale_linetype_manual(name = NULL, values = c("National Total" = "dashed", 
                                                "State" = "solid"))+
  scale_x_continuous(breaks = seq(2021,2025,1))+
  scale_y_continuous(trans = 'log10', labels = scales::comma,breaks = c(1000,2500,5000,10000,20000))+
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "top",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "U.S. and State Peanut Acres Planted, 2021-2025", 
       caption  = "Source: USDA NASS",
       x = "Year",
       y = "Acres planted (thousands)")
  
```



```{r}
consTill_state <- read.csv("consTill_state.csv")

consTill_state_w <- consTill_state |> 
  janitor::clean_names() |> 
  dplyr::select(year,state,value,cv) |> 
  mutate(value = as.numeric(gsub(",","",value)))
```
```{r}
group_color <- c("GEORGIA" = "#BA0C2F", "FLORIDA" = "#FA4616", "ALABAMA" = "#828A8F")
```

```{r}
label_data1 <- consTill_state_w |> 
  mutate(value_k = value/1000) |> 
  filter(year == 2022)

consTill_state_w |>
   mutate(value_k = value/1000) |> 
  #        line_type = if_else(state == "US TOTAL", "National Total", "State")) |> 
  ggplot(aes(year,value_k, color = state))+
  geom_point(size = 2)+
  geom_line(linewidth = 0.8)+
  geom_text_repel(
    data = label_data1,
    aes(label = str_to_title(state)),  # converts "GEORGIA" to "Georgia"
    nudge_x = 0.3,
    direction = "y",
    hjust = 0,
    segment.size = 0
  ) +
 scale_x_continuous(
  breaks = c(2012, 2017, 2022),
  limits = c(2011, 2024),
  expand = expansion(mult = 0)
)+
  scale_color_manual(name = "State",
                     values = group_color) +
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "none",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Conservation Till in Southern States, 2012-2022", 
       caption  = "Source: USDA NASS Census (2012,2017,2022)",
       x = "Year",
       y = "Acres (thousands)")
```
```{r}
consTill_state_w |> 
  mutate(year = factor(year),
         value_k = value/1000) |> 
  ggplot(aes(state,value_k, fill = year))+
  geom_col(position = "dodge")+
  scale_fill_manual(name = "Year",
    values = c("2012" = "#d4a96a", "2017" = "#8c6d3f", "2022" = "#3d2b1f"))+
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "top",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Conservation Tillage in Southern States, 2012-2022", 
       caption  = "Source: USDA NASS Census (2012,2017,2022)",
       x = element_blank(),
       y = "Acres (thousands)")
```

```{r}
coverCrop_state <- read.csv("coverCrop_state.csv")

coverCrop_state_w <- coverCrop_state |> 
  janitor::clean_names() |> 
  dplyr::select(year,state,value,cv) |> 
  mutate(value = as.numeric(gsub(",","",value)))
```

```{r fig.width=5, fig.height=4}

label_data2 <- coverCrop_state_w |> 
  mutate(value_k = value/1000) |> 
  filter(year == 2022)

coverCrop_state_w|>
   mutate(value_k = value/1000) |> 
  #        line_type = if_else(state == "US TOTAL", "National Total", "State")) |> 
  ggplot(aes(year,value_k, color = state))+
  geom_point(size = 2)+
  geom_line(linewidth = 0.8)+
  geom_text_repel(
    data = label_data2,
    aes(label = str_to_title(state)),  # converts "GEORGIA" to "Georgia"
    nudge_x = 0.2,
    direction = "y",
    hjust = 0,
    segment.size = 0
  ) +
  scale_x_continuous(
  breaks = c(2012, 2017, 2022),
  limits = c(2011, 2024),
  expand = expansion(mult = 0)
)+
  scale_color_manual(name = "State",
    values = group_color) +
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "none",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Cover Crop in Southern States, 2012-2022", 
       caption  = "Source: USDA NASS Census (2012,2017,2022)",
       x = "Year",
       y = "Acres (thousands)")
```
```{r}
coverCrop_state_w |> 
  mutate(year = factor(year),
         value_k = value/1000) |> 
  ggplot(aes(state,value_k, fill = year))+
  geom_col(position = "dodge")+
  scale_fill_manual(name = "Year",
    values = c("2012" = "#d4a96a", "2017" = "#8c6d3f", "2022" = "#3d2b1f"))+
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "top",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Cover Crop in Southern States, 2012-2022", 
       caption  = "Source: USDA NASS Census (2012,2017,2022)",
       x = "State",
       y = "Acres (thousands)")
```

```{r}
consTill_county <- read.csv("consTill_county.csv")

coverCrop_county <- read.csv("covercrop_county.csv")
```

```{r}
consTill_county_w <- consTill_county |> 
  janitor::clean_names() |> 
  select(year,state,ag_district,county,value,cv) |> 
  mutate(value = as.numeric(gsub(",","",value)),
         county = str_to_title(county),
         year = factor(year))

coverCrop_county_w <- coverCrop_county |> 
  janitor::clean_names() |> 
  select(year,state,ag_district,county,value,cv) |> 
  mutate(value = as.numeric(gsub(",","",value)),
         county = str_to_title(county),
         year = factor(year))
```

```{r}
consTill_county_w[is.na(consTill_county_w$value),]
```

```{r}
consTill_county_w |> 
  group_by(state,year) |> 
  top_n(3,value)
```

```{r}
peanut_county <- read.csv("peanut_county.csv")
```

```{r}
peanut_county_w <- peanut_county |> 
  janitor::clean_names() |> 
  select(year,state,ag_district,county,value) |> 
  mutate(value = as.numeric(gsub(",","",value)),
         county = str_to_title(county),
         year = factor(year))
```

```{r}
top_three <- peanut_county_w |> 
  group_by(state,year) |> 
  top_n(3,value) |> 
  ungroup()
```

```{r}
top_three|> 
  group_by(state,year) |> 
  mutate(value_k = value/1000) |> 
  summarise(sum = sum(value_k, na.rm = TRUE)) |> 
  ungroup() |> 
  ggplot(aes(state,sum,fill = year))+
  geom_col(position = "dodge")+
  scale_fill_manual(name = "Year",
    values = c("2012" = "#d4a96a", "2017" = "#8c6d3f", "2022" = "#3d2b1f"))+
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "top",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Peanut Production in top three counties, 2012-2022", 
       caption  = "Source: USDA NASS Census (2012,2017,2022)",
       x = "State",
       y = "Acres harvested (thousands)")
```

```{r}
top_three_consTill <- top_three |> 
  left_join(consTill_county_w, by = c("county","state","year"))

top_three_coverCrop <- top_three |> 
  left_join(coverCrop_county_w, by = c("county","state","year"))
```

```{r}
top_three_consTill |> 
  filter(!year == 2012) |> 
  group_by(state,year) |> 
  mutate(value_k = value.y/1000) |> 
  summarise(sum = sum(value_k, na.rm = TRUE)) |> 
  ungroup() |> 
  ggplot(aes(state,sum,fill = year))+
  geom_col(position = "dodge")+
  scale_fill_manual(name = "Year",
    values = c("2017" = "#8c6d3f", "2022" = "#3d2b1f"))+
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "top",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Conservation tillage in top three counties, 2017-2022", 
       caption  = "Source: USDA NASS Census (2017,2022)",
       x = "State",
       y = "Acres harvested (thousands)")
```
```{r}
top_three_coverCrop |> 
  filter(!year == 2012) |> 
  group_by(state,year) |> 
  mutate(value_k = value.y/1000) |> 
  summarise(sum = sum(value_k, na.rm = TRUE)) |> 
  ungroup() |> 
  ggplot(aes(state,sum,fill = year))+
  geom_col(position = "dodge")+
  scale_fill_manual(name = "Year",
    values = c("2017" = "#90EE90", "2022" = "#32CD32"))+
  theme_minimal(base_size = 12)+
  theme(plot.title = element_text(face = "bold"),
        legend.position = "top",
        panel.grid.minor = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA))+
  labs(title = "Cover Crop Adoption in top three counties, 2017-2022", 
       caption  = "Source: USDA NASS Census (2017,2022)",
       x = "State",
       y = "Acres harvested (thousands)")
```

